# Generated by Django 4.2.3 on 2023-07-09 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_floor', models.PositiveIntegerField(default=0)),
                ('is_under_maintainance', models.BooleanField(default=False)),
                ('door_status', models.CharField(choices=[('Open', 'Open'), ('closed', 'closed')], default='Closed')),
                ('elevator_status', models.CharField(choices=[('Going_up', 'Going_up'), ('Going_down', 'Going_down'), ('Halt', 'Halt')], default='Halt')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.system')),
            ],
        ),
    ]
