# Generated by Django 4.2.3 on 2023-07-10 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0002_request_elevator_next_floor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
