# Generated by Django 4.2.3 on 2023-07-10 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0003_delete_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up_floor', models.BigIntegerField()),
                ('destination_floor', models.BigIntegerField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Fulfilled', 'Fulfilled')], default='Active')),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elevator.elevator')),
            ],
        ),
    ]
