# Generated by Django 4.2.3 on 2023-07-10 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0004_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='destination_floor',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='elevator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elevator.elevator'),
        ),
    ]
