# Generated by Django 4.2.3 on 2023-07-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0005_alter_request_destination_floor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='elevator_status',
            field=models.CharField(choices=[('Going_up', 'Going_up'), ('Going_down', 'Going_down'), ('Idle', 'Idle')], default='Idle'),
        ),
        migrations.AlterField(
            model_name='elevator',
            name='next_floor',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
