# Generated by Django 4.2.3 on 2023-07-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0006_alter_elevator_elevator_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='door_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Closed'),
        ),
    ]
