# Generated by Django 4.2.3 on 2023-07-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0007_alter_elevator_door_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Boarded', 'Boarded'), ('Fulfilled', 'Fulfilled')], default='Active'),
        ),
    ]
